apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: default
  labels:
    app: otel-collector
spec:
  type: ClusterIP
  ports:
    - name: otlp
      port: 4317
    - name: otlp-http
      port: 4318
  selector:
    app: otel-collector
  internalTrafficPolicy: Cluster
